### ISSUE TITLE
Error using plugin in cakephp 3.0

### ISSUE THREAD

**Issue by aguirre1017** [FriendsOfCake/CakePdf#140]
After following the proper configuration for using this plugin on my cakephp 3.0 project, I am encountering the error below. What seems to be the problem? Thanks!

```
Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing. #0 D:\xampp\htdocs\vendor\cakephp\cakephp\src\View\View.php(576): Cake\View\View->_getViewFileName('error500') #1 D:\xampp\htdocs\vendor\friendsofcake\cakepdf\src\View\PdfView.php(117): Cake\View\View->render('error500', 'error') #2 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(358): CakePdf\View\PdfView->render('error500', 'error') #3 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(327): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #4 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Error\ExceptionRenderer->_outputMessage('error500') #5 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(194): Cake\Error\ExceptionRenderer->_outputMessage('fatalError') #6 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(144): Cake\Error\ExceptionRenderer->render() #7 D:\xampp\htdocs\vendor\cakephp\c in D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 156
```

**Comment by luisguerra** [comment]
Copy your file /src/Template/Error/error500.ctp to /src/Template/Error/pdf/error500.ctp 

It will not resolve your problem but will give you a more proper output to find your error

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/8099
