### ISSUE TITLE
not rendering

### ISSUE THREAD

**Issue by dmb1416** [FriendsOfCake/CakePdf#198]
So i installed CakePdf and i go to /quotes/buildpdf/4.pdf    and it loads a pdf header so chrome opens in Reader  but it says Failed to Load PDF Document... if i view the source it just has the text output it's not rendered as a PDF... wkhtmltopdf  is installed and i added the configuration array to /config/app.php

```
'CakePdf' => [
        'engine' => 'CakePdf.WkHtmlToPdf',
        'binary' => '/usr/local/bin/wkhtmltopdf',
        'margin' => [
            'bottom' => 15,
            'left' => 50,
            'right' => 30,
            'top' => 45
        ],
        'orientation' => 'portrait',
        'download' => true
    ],
```

**Comment by dpkrai96** [comment]
Same problem here too.

**Comment by dakota** [comment]
This might be related to the problem that I am having too. 3.2.1 works 100%, but 3.2.2 consistently fails with the error:

```
2017-02-15 05:08:06 Error: [Cake\Core\Exception\Exception] System error "libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
" when executing command "/home/vagrant/wkhtmltox/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A4' --encoding 'UTF-8' --margin-bottom '0mm' --margin-left '0mm' --margin-right '0mm' --margin-top '0mm' --dpi '150' - -". Try using the binary provided on http://wkhtmltopdf.org/downloads.html
Request URL: xxx
Referer URL: http://xxx
Client IP: 192.168.13.1
Stack Trace:
#0 /vagrant/apps/ynm/vendor/friendsofcake/cakepdf/src/Pdf/CakePdf.php(298): CakePdf\Pdf\Engine\WkHtmlToPdfEngine->output()
#1 /vagrant/apps/ynm/vendor/friendsofcake/cakepdf/src/View/PdfView.php(119): CakePdf\Pdf\CakePdf->output('<html>\n<head>\n ...')
#2 /vagrant/apps/ynm/vendor/cakephp/cakephp/src/Controller/Controller.php(617): CakePdf\View\PdfView->render(NULL, NULL)
#3 /vagrant/apps/ynm/vendor/croogo/croogo/Core/src/Controller/AppController.php(107): Cake\Controller\Controller->render(NULL, NULL)
#4 /vagrant/apps/ynm/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(127): Croogo\Core\Controller\AppController->render()
#5 /vagrant/apps/ynm/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(Listings\Controller\ListingsController))
#6 /vagrant/apps/ynm/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(60): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 /vagrant/apps/ynm/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#8 {main}
```

Please check your error logs to see if you have the same error message. Could you also try install 3.2.1 instead of 3.2.2 and see if that helps.

This seems to be directly related to the change in error handling that was done in 3.2.2

**Comment by ADmad** [comment]
@dakota This issue was posted 5 days ago and 3.2.2 was released 4 days ago so your problem is not related. But I can take care of it, please just let me know what's the [return](https://github.com/FriendsOfCake/CakePdf/blob/master/src/Pdf/Engine/WkHtmlToPdfEngine.php#L76) generated.

**Comment by ADmad** [comment]
Closing as the issue has gone stale.
